sudo: false
rvm: 2.3.0
bundler_args: "--without debug development"
cache: bundler
addons:
  postgresql: 9.4
before_script:
- cp config/database.travis.yml config/database.yml
- cp .travis.env .env
- bundle exec rake db:create
- bundle exec rake db:migrate
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
